openapi: 3.0.0
info:
  version: "1.0.0"
  title: 'Service Account'
  description: 'ServiceAccount Microservice API'
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/aaxis/TelcoServiceAccount/1.0.0

paths:

  /serviceAccounts:
    post:
      description: Create or Update Service Account
      requestBody:
        description: description
        content:
            "application/json":
              schema:
                $ref: './TelcoDomain.yaml#/definitions/ServiceAccount'
      responses:
        200:
          description: Ok
        400:
          description: InvalidRequest

  /customerAccounts/{id}/serviceAccount/{serviceid}:
    get:
      description: Get Service Account
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: object
        - name: serviceid
          in: path
          required: true
          schema:
            type: object
      responses:
        200:
          description: The Service Account info
          content:
            application/json:
              schema:
               $ref: './TelcoDomain.yaml#/definitions/ServiceAccount'
        404:
          description: NotFound